In [18]:
import pandas as pd
import numpy as np

In [19]:
quantidade_produtos = [3,5,6,10]
precos_produtos = [10,5,7,100]

array_produtos = np.array(quantidade_produtos)
array_precos = np.array(quantidade_produtos)

faturamento = array_produtos * array_precos
print(faturamento)

[  9  25  36 100]

In [20]:
quantidade_produtos = [3,5,6,10]
precos_produtos = [10,5,7,100]
nomes_produtos = ["pastel","caçulinha","refrigerante","combos"]

array_produtos = np.array(quantidade_produtos)
array_precos = np.array(precos_produtos)

faturamento = array_produtos * array_precos
for nome, preco in zip(nomes_produtos, faturamento):
    print(f"{nome} : {preco}")

pastel : 30
caçulinha : 25
refrigerante : 42
combos : 1000

### Exercício de fixação

- criar uma lista qu irá possuir 10 nomes de produtos.
- criar uma lista que irá possuir o preço de custo(atacado).
- criar uma lista que irá possuir o preço de venda (varejo).
- ao final, exibir o lucro obtido em cada produto.

In [21]:
precos_varejo = [23.90, 7.50, 7.90, 4.90, 5.90, 16.90, 5.20, 4.50, 2.50, 2.90 ]
precos_atacado = [18.50, 6, 6.40, 3.90, 4.80, 13.80, 4.20, 3.40, 1.90, 2.20]
nomes_produtos = ["arroz", "feijão","óleo de soja", "açúcar", "farinha de trigo", "café", "leite integral", "macarraão espaguete", "molho de tomate", "sal"]

array_varejo = np.array(precos_varejo)
array_atacado = np.array(precos_atacado)

faturamento = array_varejo - array_atacado
for nome, preco in zip(nomes_produtos, faturamento):
    print(f"o lucro do produto {nome} foi {preco:.2f}")

o lucro do produto arroz foi 5.40
o lucro do produto feijão foi 1.50
o lucro do produto óleo de soja foi 1.50
o lucro do produto açúcar foi 1.00
o lucro do produto farinha de trigo foi 1.10
o lucro do produto café foi 3.10
o lucro do produto leite integral foi 1.00
o lucro do produto macarraão espaguete foi 1.10
o lucro do produto molho de tomate foi 0.60
o lucro do produto sal foi 0.70

## Pandas

In [30]:
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas.csv")

In [31]:
df.head()

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [32]:
df = pd. read_csv(r".\data\dataset_techshop_vendas (1).csv")
df.head

<bound method NDFrame.head of     data_pedido    categoria  preco_unitario  quantidade    regiao  \
0    2024-01-01   Acessórios           36.20           1   Sudeste
1    2024-01-01   Acessórios          122.61           5   Sudeste
2    2024-01-02   Acessórios          151.19           4       Sul
3    2024-01-03          TVs         3399.16           2   Sudeste
4    2024-01-04  Smartphones         3180.94           2  Nordeste
..          ...          ...             ...         ...       ...
795  2024-12-27        Áudio         1128.44           4       Sul
796  2024-12-27   Acessórios          209.29           4   Sudeste
797  2024-12-28    Notebooks         7979.84           2   Sudeste
798  2024-12-28    Notebooks         4168.01           1  Nordeste
799  2024-12-28   Acessórios          111.95           1       Sul

    canal_marketing  avaliacao
0         Instagram        3.3
1          Orgânico        4.4
2        Google Ads        4.6
3        Google Ads        4.1
4         Instagram        3.9
..              ...        ...
795        Orgânico        4.6
796      Google Ads        3.8
797      Google Ads        4.4
798       Instagram        4.1
799      Google Ads        4.7

[800 rows x 7 columns]>

In [33]:
df.tail

<bound method NDFrame.tail of     data_pedido    categoria  preco_unitario  quantidade    regiao  \
0    2024-01-01   Acessórios           36.20           1   Sudeste
1    2024-01-01   Acessórios          122.61           5   Sudeste
2    2024-01-02   Acessórios          151.19           4       Sul
3    2024-01-03          TVs         3399.16           2   Sudeste
4    2024-01-04  Smartphones         3180.94           2  Nordeste
..          ...          ...             ...         ...       ...
795  2024-12-27        Áudio         1128.44           4       Sul
796  2024-12-27   Acessórios          209.29           4   Sudeste
797  2024-12-28    Notebooks         7979.84           2   Sudeste
798  2024-12-28    Notebooks         4168.01           1  Nordeste
799  2024-12-28   Acessórios          111.95           1       Sul

    canal_marketing  avaliacao
0         Instagram        3.3
1          Orgânico        4.4
2        Google Ads        4.6
3        Google Ads        4.1
4         Instagram        3.9
..              ...        ...
795        Orgânico        4.6
796      Google Ads        3.8
797      Google Ads        4.4
798       Instagram        4.1
799      Google Ads        4.7

[800 rows x 7 columns]>

In [34]:
df.shape

(800, 7)

In [35]:
df. info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    str
 1   categoria        800 non-null    str
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    str
 5   canal_marketing  800 non-null    str
 6   avaliacao        800 non-null    float64
dtypes: float64(2), int64(1), str(4)
memory usage: 70.9 KB

In [36]:
df.describe()

       preco_unitario  quantidade   avaliacao
count      800.000000  800.000000  800.000000
mean      2173.764038    2.237500    4.165500
std       2042.173946    1.306034    0.542658
min         20.070000    1.000000    2.400000
25%        249.837500    1.000000    3.800000
50%       1458.565000    2.000000    4.200000
75%       3707.427500    3.000000    4.600000
max       7979.840000    5.000000    5.000000

In [60]:
import pandas as pd
import numpay as np

In [61]:
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas.csv")

In [62]:
df

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0             1  Montagem          72.62          41.77           111      0
1             2  Usinagem          81.65          34.08           128      0
2             3  Usinagem          68.87          39.44           159      0
3             4  Usinagem          66.84          34.52            98      0
4             5  Usinagem          66.23          31.57            94      0
5             6  Usinagem          64.79          37.09            83      0
6             7  Usinagem          85.02          36.34           106      1
7             8  Inspeção          60.31          33.77           124      0
8             9  Montagem          75.84          29.65            92      0
9            10  Inspeção          68.38          28.93           145      1
10           11  Usinagem          76.31          35.48           149      0
11           12  Inspeção          74.79          33.37           134      0
12           13  Usinagem          76.31          36.51           154      0
13           14  Montagem          63.28          33.71           129      0
14           15  Montagem          64.98          33.24            83      0
15           16  Montagem          81.48          30.50           102      0
16           17  Montagem          79.62          39.68            85      1
17           18  Inspeção          69.80          27.20            91      0
18           19  Inspeção          77.16          47.45            99      0
19           20  Usinagem          73.30          39.77           119      1
20           21  Inspeção          79.77          38.04            91      0
21           22  Usinagem          71.76          35.16            80      0
22           23  Inspeção          74.16          31.93           149      0
23           24  Usinagem          74.69          32.34           123      1
24           25  Usinagem          74.03          32.71           145      1
25           26  Usinagem          75.96          38.70            93      0
26           27  Usinagem          60.80          37.18           159      0
27           28  Montagem          69.37          35.90           122      1
28           29  Montagem          70.28          35.04           103      0
29           30  Inspeção          73.53          32.84            82      0
30           31  Montagem          63.59          42.29           159      1
31           32  Inspeção          68.91          32.66           155      0
32           33  Inspeção          77.62          35.70           108      1
33           34  Inspeção          73.32          32.18           129      1
34           35  Usinagem          78.24          31.93           158      0
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [63]:
df. head()

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [64]:
df. info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    40 non-null     int64
 1   setor          40 non-null     str
 2   temperatura_c  40 non-null     float64
 3   tempo_ciclo_s  40 non-null     float64
 4   producao_dia   40 non-null     int64
 5   falha          40 non-null     int64
dtypes: float64(2), int64(3), str(1)
memory usage: 2.3 KB